# Generated by Django 5.2 on 2025-04-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_resorts_room_resort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resort_name', to='booking.resorts'),
            preserve_default=False,
        ),
    ]
